name: oksigenia_sos
description: "Oksigenia SOS - Outdoor Emergency Assistant"
publish_to: 'none'
version: 3.6.0+2002

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Core Logic
  geolocator: ^13.0.1
  url_launcher: ^6.3.1
  permission_handler: ^12.0.1
  wakelock_plus: ^1.2.8  # <--- NUEVO: Para mantener la pantalla encendida
  
  # Sensors & Audio
  sensors_plus: ^6.1.0       
  audioplayers: ^6.0.0       
  vibration: ^3.1.5          

  # State & UI
  shared_preferences: ^2.3.2 
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/sounds/
    - assets/images/

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21
