name: oksigenia_sos
description: "Oksigenia SOS - Outdoor Emergency Assistant"
publish_to: 'none'
version: 3.7.1+18

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: 3.38.7

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Core Logic & Background (MOVIDO AQUÍ)
  flutter_background_service: ^5.0.0
  geolocator: ^13.0.1
  url_launcher: ^6.3.1
  permission_handler: ^12.0.1
  wakelock_plus: ^1.2.8
  
  # Sensors & Audio
  sensors_plus: ^6.1.0       
  audioplayers: ^6.0.0       
  vibration: ^3.1.5          

  # State & UI
  shared_preferences: ^2.3.2 
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/sounds/
    - assets/images/

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/icon.png" # Para Androids antiguos (Legacy)
  min_sdk_android: 21

  # --- CONFIGURACIÓN ADAPTATIVA ---
  # Esto genera el XML que separa fondo y frente, igual que Proton Mail.
  adaptive_icon_background: "#FFFFFF"  # Fondo Blanco Puro
  adaptive_icon_foreground: "assets/images/icon_foreground.png" # El logo con fondo transparente
