name: oksigenia_sos
description: "Outdoor Emergency Assistant"
publish_to: 'none'
version: 3.9.4+30904

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.38.7"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Core Logic & Background (MOVIDO AQUÃ)
  flutter_background_service: ^5.0.0
  geolocator: ^13.0.1
  url_launcher: ^6.3.1
  permission_handler: ^12.0.1
  wakelock_plus: ^1.2.8
  
  # Sensors & Audio
  sensors_plus: ^6.1.0       
  audioplayers: ^6.0.0       
  vibration: ^3.1.5          

  # State & UI
  shared_preferences: ^2.5.4 
  cupertino_icons: ^1.0.8
  battery_plus: ^7.0.0
  http: ^1.6.0
  package_info_plus: ^9.0.0
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/sounds/
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "assets/icon/ic_background.png"
  adaptive_icon_foreground: "assets/icon/ic_foreground.png"

  # ğŸ‘‡ ESTAS LÃNEAS TIENEN QUE ESTAR ACTIVAS (SIN #) ğŸ‘‡
  notification_icon: "ic_stat_oksigenia"
  image_path_android: "assets/images/logo_white.png"
